const { Product } = require('../models');

const productData = [
  {
    product_name: 'Double Breasted Beige men shirt',
    product_desc:"Tailored V neck notch lapel double breasted beige 2-Piece business suit made from high-quality potrueer fabric. It comes with bottom as trouser",
    price: 14.99,
    product_spec:"Large",
    stock: 14,
    is_stock:true,
    slug:"men-shirt",
    product_image_path:"https://img.freepik.com/free-photo/young-businessman-with-hands-his-pocket-holding-clipboard_23-2148190743.jpg?t=st=1693457026~exp=1693457626~hmac=aa4fe64a99ed9d96d6ed62c1a737d49bb1842d23a7eaff3faddd0f31a1c2737c",
    sub_category_id: 1,
    color_id:1
  },
  {
    product_name: 'Ethnic Printed Wedding shirt',
    product_desc:"Ethnic wear Indian designer white piping work on collar and chest pocket classic Nehru collar waistcoat made from black color printed Imported fabric",
    price: 14.99,
    product_spec:"Large",
    stock: 14,
    is_stock:true,
    slug:"men-shirt",
    product_image_path:"https://img.freepik.com/free-photo/young-handsome-businessman-posing-indoor_144627-28063.jpg?size=626&ext=jpg&ga=GA1.2.1362527255.1687744353&semt=ais",
    sub_category_id: 1,
    color_id:2
  },
  {
    product_name: 'Ethnic Printed Wedding shirt',
    product_desc:"Ethnic wear Indian designer white piping work on collar and chest pocket classic Nehru collar waistcoat made from black color printed Imported fabric",
    price: 14.99,
    product_spec:"Large",
    stock: 14,
    is_stock:true,
    slug:"men-shirt",
    product_image_path:"https://img.freepik.com/free-photo/happy-smiling-young-man-blue-shirt-blackboard_176420-2940.jpg?size=626&ext=jpg&ga=GA1.1.1362527255.1687744353&semt=ais",
    sub_category_id: 1,
    color_id:2
  },
  {
    product_name: 'Ethnic Printed Wedding Nehru Waistcoat',
    product_desc:"Ethnic wear Indian designer white piping work on collar and chest pocket classic Nehru collar waistcoat made from black color printed Imported fabric",
    price: 14.99,
    product_spec:"Large",
    stock: 14,
    is_stock:true,
    slug:"men-trousers",
    product_image_path:"https://img.freepik.com/free-photo/young-handsome-businessman-posing-indoor_144627-28063.jpg?size=626&ext=jpg&ga=GA1.2.1362527255.1687744353&semt=ais",
    sub_category_id: 2,
    color_id:2
  },
  {
    product_name: 'Ethnic Printed Wedding Nehru Waistcoat',
    product_desc:"Ethnic wear Indian designer white piping work on collar and chest pocket classic Nehru collar waistcoat made from black color printed Imported fabric",
    price: 14.99,
    product_spec:"Large",
    stock: 14,
    is_stock:true,
    slug:"men-trousers",
    product_image_path:"https://img.freepik.com/free-photo/young-handsome-businessman-posing-indoor_144627-28063.jpg?size=626&ext=jpg&ga=GA1.2.1362527255.1687744353&semt=ais",
    sub_category_id: 2,
    color_id:1
  },
  {
    product_name: 'Ethnic Printed Wedding Nehru Waistcoat',
    product_desc:"Ethnic wear Indian designer white piping work on collar and chest pocket classic Nehru collar waistcoat made from black color printed Imported fabric",
    price: 14.99,
    product_spec:"Large",
    stock: 14,
    is_stock:true,
    slug:"men-trousers",
    product_image_path:"https://img.freepik.com/free-photo/young-handsome-businessman-posing-indoor_144627-28063.jpg?size=626&ext=jpg&ga=GA1.2.1362527255.1687744353&semt=ais",
    sub_category_id: 2,
    color_id:3
  },
  {
    product_name: 'Stylish blazer',
    product_desc:"Jennifer Winget looks more beutiful in this blue satin silk anarkali gown with embroidered floral motifs on the yoke",
    price: 14.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"men-blazer",
    product_image_path:"https://media.istockphoto.com/id/1422546700/photo/fashion-model-in-red-evening-dress-beautiful-woman-in-princess-ball-gown-and-curly-hairstyle.jpg?b=1&s=170667a&w=0&k=20&c=jYyJ7Cp8nEDa_KhgZFTjKXRomXsdvx9TGOxa_-YquOo=",
    sub_category_id: 3,
    color_id:3
  },
  {
    product_name: 'Stylish blazer',
    product_desc:"Jennifer Winget looks more beutiful in this blue satin silk anarkali gown with embroidered floral motifs on the yoke",
    price: 14.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"men-blazer",
    product_image_path:"https://media.istockphoto.com/id/1422546700/photo/fashion-model-in-red-evening-dress-beautiful-woman-in-princess-ball-gown-and-curly-hairstyle.jpg?b=1&s=170667a&w=0&k=20&c=jYyJ7Cp8nEDa_KhgZFTjKXRomXsdvx9TGOxa_-YquOo=",
    sub_category_id: 3,
    color_id:3
  },
  {
    product_name: 'Stylish blazer',
    product_desc:"Jennifer Winget looks more beutiful in this blue satin silk anarkali gown with embroidered floral motifs on the yoke",
    price: 14.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"men-blazer",
    product_image_path:"https://media.istockphoto.com/id/1422546700/photo/fashion-model-in-red-evening-dress-beautiful-woman-in-princess-ball-gown-and-curly-hairstyle.jpg?b=1&s=170667a&w=0&k=20&c=jYyJ7Cp8nEDa_KhgZFTjKXRomXsdvx9TGOxa_-YquOo=",
    sub_category_id: 3,
    color_id:3
  },
  {
    product_name: 'Grey And Black women blazer',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 14.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"women-blazer",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 4,
    color_id:2
  },
  {
    product_name: 'Grey And Black women blazer',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 14.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"women-blazer",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 4,
    color_id:2
  },
  {
    product_name: 'Grey And Black women blazer',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Medium",
    stock: 10,
    is_stock:true,
    slug:"women-blazer",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 4,
    color_id:1
  },
  {
    product_name: 'Grey And Black women blazer',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Medium",
    stock: 10,
    is_stock:true,
    slug:"women-blazer",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 4,
    color_id:3
  },
  {
    product_name: 'Grey And Black women shirts',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Small",
    stock: 10,
    is_stock:true,
    slug:"women-shirt",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 5,
    color_id:3
  },
  {
    product_name: 'Grey And Black women shirts',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Small",
    stock: 10,
    is_stock:true,
    slug:"women-shirt",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 5,
    color_id:2
  },
  {
    product_name: 'Grey And Black women shirts',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Small",
    stock: 10,
    is_stock:true,
    slug:"women-shirt",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 5,
    color_id:2
  },
  {
    product_name: 'Grey And Black women trousers',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Small",
    stock: 10,
    is_stock:true,
    slug:"women-trousers",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 6,
    color_id:3
  },
  {
    product_name: 'Grey And Black women trousers',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Small",
    stock: 10,
    is_stock:true,
    slug:"women-trousers",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 6,
    color_id:3
  },
  {
    product_name: 'Grey And Black women trousers',
    product_desc:"A horizontal self-striped black and grey pre draped lycra saree embellished with thread, cord embroidery and applique work",
    price: 100,
    product_spec:"Small",
    stock: 10,
    is_stock:true,
    slug:"women-trousers",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 6,
    color_id:3
  },
  {
    product_name: 'girls stylish Gown',
    product_desc:"Jennifer Winget looks more beutiful in this blue satin silk anarkali gown with embroidered",
    price: 14.99,
    product_spec:"[small,medium]",
    stock: 10,
    is_stock:true,
    slug:"Stylish Blue Embroidered Gown",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 7,
    color_id:1
  },
  {
    product_name: 'girls stylish Gown',
    product_desc:"Jennifer Winget looks more beutiful in this blue satin silk anarkali gown with embroidered",
    price: 14.99,
    product_spec:"[small,medium]",
    stock: 10,
    is_stock:true,
    slug:"girls-dresses",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 7,
    color_id:1
  },
  {
    product_name: 'girls stylish Gown',
    product_desc:"Jennifer Winget looks more beutiful in this blue satin silk anarkali gown with embroidered",
    price: 14.99,
    product_spec:"small",
    stock: 10,
    is_stock:true,
    slug:"girls-dresses",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 7,
    color_id:1
  },
  {
    product_name: 'girls stylish Gown',
    product_desc:"Jennifer Winget looks more beutiful in this blue satin silk anarkali gown with embroidered",
    price: 14.99,
    product_spec:"small",
    stock: 10,
    is_stock:true,
    slug:"girls-dresses",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 7,
    color_id:1
  },
  {
    product_name: 'Grey And Black Frock',
    product_desc:"A horizontal self-striped black and grey Frock",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-frocks",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 8,
    color_id:3
  },
  {
    product_name: 'Grey And Black Frock',
    product_desc:"A horizontal self-striped black and grey Frock",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-frocks",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 8,
    color_id:2
  },
  {
    product_name: 'Grey And Black Frock',
    product_desc:"A horizontal self-striped black and grey Frock",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-frocks",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 8,
    color_id:1
  },
  {
    product_name: 'Grey TOp',
    product_desc:"A horizontal self-striped black and grey Frock",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-top",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 9,
    color_id:1
  },
  {
    product_name: 'Grey TOp',
    product_desc:"A horizontal self-striped black and grey Frock",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-top",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 9,
    color_id:2
  },
  {
    product_name: 'Grey TOp',
    product_desc:"A horizontal self-striped black and grey Frock",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-top",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 9,
    color_id:3
  },
  {
    product_name: 'Grey TRousers',
    product_desc:"A horizontal self-striped black and grey Trousers",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-trousers",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 10,
    color_id:3
  },
  {
    product_name: 'Grey TRousers',
    product_desc:"A horizontal self-striped black and grey Trousers",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-trousers",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 10,
    color_id:2
  },
  {
    product_name: 'Grey TRousers',
    product_desc:"A horizontal self-striped black and grey Trousers",
    price: 24.99,
    product_spec:"Large",
    stock: 10,
    is_stock:true,
    slug:"girl-trousers",
    product_image_path:"https://cdn.pixabay.com/photo/2017/08/28/02/59/suit-2688317_1280.jpg",
    sub_category_id: 10,
    color_id:1
  },

  
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
